name: ${project.name}
main: com.github.civcraft.dogfacts.DogFactsPlugin
author: Maxopoly
version: ${project.version}
depend: [CivModCore]
softdepend: []
commands:
  dfreload:
    permission: df.op
permissions:
  df.op:
    default: op
